#!/usr/bin/env python

"""
PLOT MESH OBJECTS
plots that derive from the Delaunay mesh objects generated by codes/mesh.py
"""

#---block: what to plot
routine = ['review3d','curvature','curvature-radial'][1:2]

#---block: load the calculation data
if 'data' not in globals(): 
	data,calcs = plotload('mesh',work)

