#!/usr/bin/env python

"""
PLOT MESH OBJECTS
plots that derive from the Delaunay mesh objects generated by codes/mesh.py
"""

routine = ['review3d','cellplot'][:1]

#---load everything
if 'data' not in globals(): 
	data,calcs = plotload(plotname,work)

if 'review3d' in routine:

	from codes.review3d import review3d

	sn = 'mk002'
	dat = data[sn]['data']
	pts = dat['1.1.points']
	review3d(lines=[pts],points=[pts],tube=0.02,radius=0.2)
	
if 'cellplot' in routine:

	from codes.cellplot import cellplot

	sn = 'mk002'
	dat = data[sn]['data']
	mn,fr = 1,10

	simps = dat['%d.%d.simplices'%(mn,fr)]
	pts = dat['%d.%d.points'%(mn,fr)]
